site.nix
themes/fractalide/templates/blocks/news.nix
themes/fractalide/templates/partials/content-pre.nix

Fixes #3 
Solution: Use the localized layouts

Problem: clicking on two links from the chinese mode returns to english mode

---

data/eng/blocks/whitepaper.nix
data/zho/blocks/whitepaper.nix
themes/fractalide/templates/blocks/whitepaper.nix

Solution: put the content back into data

Problem: Whitepaper template was containing data

---

conf.nix
site.nix

Problem: siteUrl and CNAME domain were not matching

---

data/eng/pages/faq.nix
data/zho/pages/faq.nix
site.nix
themes/fractalide/lib.nix
themes/fractalide/templates/news/block.nix

Solution: Cleanup site.nix
Still not perfect, but still an improvement...

Problem: the multi-locale code in site.nix needed a cleanup

---

site.nix

Solution: Use theme from GitHub
Sorry, I forgot to commit that change in the previous PR.

Problem: site.nix was using a local theme

---

site.nix

Solution: update to a more recent styx version
Note: This change is mostly cosmetic and don't change any functionality.

Problem: site.nix was using ad-hoc code

---

data/jpn/pdf/whitepaper.tex
site.nix

Solution: Translate the whitepaper in Japanese

Problem: The whitepaper was not translated in Japanese

---

site.nix

Problem: website didn't reference new updated quickstart docs

---

fractalide-hugo-theme/README.md

Solution: add instructions to README.md [fix #26]

Problem: no clear way to run the `hugo server -D`

---

fractalide-hugo-theme/exampleSite/data/roadmap.yml

Solution: expand on the different topics

Problem: roadmap needed elaboration

---

fractalide-hugo-theme/exampleSite/data/team/denis.yml
fractalide-hugo-theme/exampleSite/data/team/elaine.yml
fractalide-hugo-theme/exampleSite/data/team/eric.yml
fractalide-hugo-theme/exampleSite/data/team/roy.yml
fractalide-hugo-theme/exampleSite/data/team/silviu.yml

Solution: add github, gitlab and twitter links

Problem: team didn't have info links

---

fractalide-hugo-theme/exampleSite/data/roadmap.yml
fractalide-hugo-theme/layouts/roadmap/single.html
fractalide-hugo-theme/static/css/bootstrap-fractalide.min.css
fractalide-hugo-theme/static/css/custom.css

Roadmap updates:
- Fix UI mobile design
- Add progress bar

Hugo theme: Roadmap updates

---

new-site/conf.nix
new-site/site.nix
new-site/themes/fractalide/files/css/bootstrap-fractalide.min.css
new-site/themes/fractalide/files/css/custom.css
new-site/themes/fractalide/templates/partials/head/css-custom.nix
new-site/themes/fractalide/templates/partials/head/title.nix

Solution: Activate bootstrap, font-awesome and googlefonts, and add our
fractalide CSS.

Problem: new-site page head lacks CSS links

---

new-site/conf.nix
new-site/data/nav.nix
new-site/themes/fractalide/templates/partials/content-pre.nix
new-site/themes/fractalide/templates/partials/nav.nix

Solution: Add menu definitions as data/nav.nix, port header.html to partials/nav.nix.

Problem: no nav header

---

new-site/themes/fractalide/templates/partials/nav.nix

Solution: strip trailing index.html from page.path when comparing with menu links.

Problem: /index.html is not recognized by nav as current page for /

---

new-site/content/roadmap.md
new-site/default.nix
new-site/nixpkgs.nix
new-site/site.nix

Solution: Render roadmap from fractalide/fractalide CHANGELOG.json.

Problem: new-site: no roadmap page 

---

fractalide-hugo-theme/layouts/fractalmarket/single.html
fractalide-hugo-theme/layouts/roadmap/single.html
new-site/content/roadmap.md
new-site/themes/fractalide/files/css/custom.css

Solution: overwrite nix css with hugo css file

Problem: nix css is older than hugo css file

---

new-site/conf.nix
new-site/data/blog/2017-07-10-reusability.md
new-site/data/blog/2017-07-13-reproducibility.md
new-site/site.nix
new-site/themes/fractalide/templates/blog/full.nix
new-site/themes/fractalide/templates/blog/index.nix
new-site/themes/fractalide/templates/blog/list.nix

Solution: Bring over templates and content from production site.

Problem: no blog pages

---

new-site/conf.nix
new-site/content/404.md
new-site/site.nix

Solution: Implement it.
It differs from hugo because I let it use the site layout. I believe
it's the right thing to do.

Problem: new-site: no 404.html

---

fractalide-hugo-theme/exampleSite/preview.sh
new-site/preview.sh

Problem: no unified shorthand for previewing hugo and new-site

---

new-site/content/faqs.md
new-site/data/faqs.nix
new-site/site.nix

Problem: new-site: no FAQ

---

new-site/content/research.md
new-site/site.nix

Problem: new-site: missing research page

---

new-site/content/contact.md
new-site/site.nix

Solution: Bring over lorem ipsum.

Problem: new-site: no contact page

---

new-site/themes/fractalide/templates/partials/nav.nix

Solution: Add a space before the chevron

Problem: new-site: navbar name<->chevron spacing differs from hugo

---

fractalide-hugo-theme/static/css/bootstrap-fractalide.min.css
new-site/conf.nix
new-site/data/nav.nix
new-site/site.nix
new-site/themes/fractalide/files/css/bootstrap-fractalide.min.css
new-site/themes/fractalide/templates/partials/nav.nix

Solution: Add link. Modify CSS so that icon is not dark grey.
Move conf...nav -> data.nav where it belongs, and where it can inherit
attributes.

Problem: no atom link in navbar

---

new-site/content/about_us/lede.nix
new-site/content/about_us/team.md
new-site/content/about_us/vision.md
new-site/site.nix
new-site/themes/fractalide/templates/page/sections.nix

Solution: Implement page/sections.
Apply it to about_us.

Problem: no template for multi-section pages

---

data/site-partials/signup.md
data/site-partials/stack.md

Solution: point them at the google sheets data capture thingy

Problem: Call To Action links go no where

---

themes/fractalide/files/css/custom.css

Solution: Update custom.css (solves issues on the mobile version of some pages including hyperflow, services and roadmap)

Problem: custom.css is not the last version

---

data/team/meredith.nix
fractalide-hugo-theme/exampleSite/data/team/meredith.yml

Solution: change it from Researcher to Security Researcher

Problem: Meredith prefers the title Security Researcher

---

preview.sh

Solution: Update ./preview.sh to use `styx live` instead of
`styx preview`.

Problem: styx ./preview.sh isn't the live preview

---

content/roadmap.md

i.e. commit c93a1b0fdf2440861f22c68942e03edb291e3e2a
Solution: Port it.
Closes #99

Problem: #63 (collapse release) not in styx

---

data/blog/2017-07-10-reusability.md
data/blog/2017-07-13-reproducibility.md
themes/fractalide/files/css/custom.css
themes/fractalide/templates/blog/full.nix
themes/fractalide/templates/blog/index.nix
themes/fractalide/templates/blog/list.nix

Solution: Update templates to apply the layout according to the site.

Problem: Blog doesn't have the right layout.

---

content/research.md
themes/fractalide/templates/blog/full.nix

Solution: Previously we just pulled in the master thesis
on the styx website, now we'll just link to the download
link on fractalide/fractalide-oz repo

Problem: Master thesis link is broken on research page

---

data/site-partials/stack.md
deploy.sh
live.sh
preview.sh

Solution: change some waffle about what fractalide is, to why it's
important.

Problem: landing page does not communicate core problem being solved

---

site.nix

Solution: update fetchFromGithub to point to latest changelog.json

Problem: new roadmap not pulled into fractalide

---

data/site-partials/stack.md

Solution: boldify the "problem" & "solution", add a sentence clarifying
where the apps run (local to your machine)

Problem: presentation bland and not clarifying the p2p nature of apps

---

content/about_us/vision.md
content/roadmap.md
data/blog/2017-07-10-reusability.md
data/blog/2017-07-13-reproducibility.md
site.nix

Solution: "0 or more" instead of "1 or more"

Problem: roadmap objectives fall when only 1 in the list

---

content/development-and-analysis.md
content/hyperflow/hyperflow.md
themes/fractalide/files/css/custom.css

Solution: fix margins for desktop version [fix #137]

Problem: layout issue for development-and-analysis and hyperflow #137

---

content/cardano-stake-pool.md

Solution: increase column to 12, providing space for inlined icons

Problem: cardano stake pool; icons on different rows

---

content/roadmap.md
data/site-partials/stack.md

Solution: elaborate on lede a bit and orient roadmap footer to "decentralized browser" instead of "app market"

Problem: lede issues 

---

content/about_us/vision.md
content/research.md
content/roadmap.md

Solution: open links in a new tab
closes #140

Problem: links take users off site

---

content/cardano-wallet/cardano-wallet.md
content/cardano-wallet/download_center.md

Solution: change download button from "Download Center" to
"Download Cantor" and elaborate on features

Problem: few typos in cardano-wallet & need of elaboration

---

data/site-partials/stack.md

Problem: lede text got too long, and CTA got bumped off the screen

---

data/site-partials/stack.md

Solution: remove it and clarify this is a dapp browser

Problem: typo in lede

---

content/404.md

Solution: The whole page was redesigned and due to a
merge conflict the incorrect page was put in. Revert it
and use the correct page

Problem: 404 page didn't compile because of the conf attr

---

content/cardano-stake-pool.md
content/community.md
content/hyperflow/hyperflow.md
content/hyperflow/hyperflow_modes.md
content/research.md
content/roadmap.md
data/nav.nix
data/site-partials/main.md
data/site-partials/stack.md
site.nix

Problem: amount of people watching the repo not present on research page

---

themes/fractalide/templates/partials/head/meta.nix

Solution: stick in a few analyitcs just to get an idea of traffic

Problem: no idea who's looking at the website

---

content/cardano-wallet/cardano-wallet.md

Solution: you send ADA.
Also mention we're using IOHK's new wallet backend

Problem: you can't send transactions

---

content/cardano-stake-pool.md

Problem: stake pool release too optimistic

---

data/nav.nix

about it
Solution: remove the ICO stuff till we're ready with the address etc

Problem: ICO link and address not ready, people are already talking

---

content/ico/comic.md
content/ico/details.md
themes/fractalide/files/js/ico.js

Solution: randomly generate an epoch from 0 to 40 inclusive

Problem: generating random epoch should not be from 0-41 inclusive

---

content/stake-pool/cardano-ada.md
content/stake-pool/cardano-luceo.md
content/stake-pool/tezos-xtz.md

Solution: Add extra margin on mobile layout.

Problem: Mobile layout needs some extra margin (fix #192)

---

default.nix

Solution: Just do callPackage.

Problem: default.nix: Convoluted call to site.nix

---

deploy.sh

Problem: deploy.sh is not in use

---

content/stake-pool/tezos-xtz.md
site.nix

Problem: No table with the staker data

---

content/stake-pool/tezos-xtz.md
test-data/default.nix

Solution: use staking address we just setup. Also
to give the page some form of dignity the table is removed
along with the "Copy" which when you clicked "Copy" it
copied itself.

Problem: fake tezos address used on XTZ staking page

---

content/stake-pool/overview.md
content/stake-pool/tezos-xtz.md
site.nix

Solution: drill into what the rewards will be used for.
Promote that we're open source and run on a secure infrastructure

Problem: XTZ stakepool blurb too vague

---

content/stake-pool/cardano-ada.md
content/stake-pool/cardano-luceo.md

Solution: Provide real headings.

Problem: luceo: Generic 'Heading' headings

---

content/stake-pool/cardano-ada.md
content/stake-pool/luceo-ceo.md
content/stake-pool/overview.md
content/stake-pool/tezos-xtz.md
data/site-partials/stack.md
themes/fractalide/templates/partials/head/meta.nix

Solution:
* added fee structures
* renamed the stakepool services
* refined the blurbs
* also changed "A Browser for a Future Internet" ->
"A Browser for an Information Centric Network"

Problem: stakepools needed reworking

---

data/blog/2018-11-23-the-semantic-gap.md

Solution: it should be Runtime Verification Inc.

Problem: Runtime Verification Ltd. is incorrect

---

content/videos.md
data/nav.nix
site.nix

Problem: video not present!

---

content/videos.md

Problem: missed the iohk video

---

content/stake-pool/tezos-xtz.md

Solution: let's get in that race and remove 8%!

Problem: stake pools are a race to 0

---

content/stake-pool/tezos-xtz.md

Solution: disable the K1 query input box leaving just the
marketing blurb and the calculator

Problem: backerei.json not properly generated - no time to fix atm

---

content/gift-details.md

Solution: treat the arrival with greater respect and
expand on the mission

Problem: gift details didn't go into sufficient detail

---

themes/fractalide/files/css/bootstrap-fractalide.min.css

Solution: Fix menu style top margin.

Problem: Menu style is broken.

---

content/gift/gift-details.md

Problem: gift details need dramatic simplification

---

content/gift/gift-instructions.md

Solution: add a --recursive to the git command

Problem: gift instructions incorrect

---

content/luceo.md

Solution: Illustrate this is our goal.

Problem: Crypsinous is a monster and should be delayed

---

data/site-partials/footer.md

Problem: copyright statement out of date

---

content/gift/gift-instructions.md

Problem: addressing is portable between blockchains

---

content/gift/gift-instructions.md

Solution: tell people to download the binary and use that instead

Problem: gift instructions are too complex - involve code compilation

---

content/gift/gift-instructions.md

Solution: make a nice link instead of something that is copy and pasted

Problem: link not clickable

---

data/blog/2019-03-13-back-to-basics.md

Solution: blog post detailing what they are and how they integrate

Problem: not enough focus on core social scalablities

---

data/blog/2019-03-13-focus-on-social-scalability.md

Solution: used the word concepts

Problem: aspects is the wrong word

---

content/community.md

Solution: remove the invite link on the site

Problem: spammers getting into the telegram channel

---

data/blog/2019-05-16-revuln-talk.md

Problem: revuln 2019 not made clear in blog title

---

content/ico/details.md
default.nix
site.nix

Solution: hack it directly via pdf, sadly it's not clear
to use racket2nix to generate a pdf from a scribble document

Problem: need a way to get the whitepaper into the website

---

nixpkgs.nix

Solution: seems like the fancy update mechanism on the server
needs this peg.

Problem: removed an apparently needed peg.

---

nixpkgs.nix
site.nix

Solution: revert peg and make it <nixpkgs> along with add whitepaper
attribute

Problem: peg not needed and forgot to stick in whitepaper into data

---

content/ico/details.md
default.nix
site.nix

Solution: remove the nix machinery and just symlink to the
paper to the root of the www directory

Problem: trouble linking the whitepaper

---

content/ico/tutorial.md

Solution: use proper formatting tags
(it's rather annoying, the ./preview.sh renders just fine.)

Problem: ico tutorial formatting messed up by mathjax

---

site.nix

Problem: political statement in jormungandr docs

---

content/ico/details.md

Problem: ICO start period of 50% is incorrect

---

content/ico/details.md

Problem: forgot to adjust sale_progress

---

content/ico/comic.md
content/ico/details.md
content/ico/tutorial.md
themes/fractalide/files/js/ico.js

Solution: brush it up and remove the problem

Problem: ico details vague and math problem too complex

---

content/ico/details.md
themes/fractalide/files/css/custom.css

Problem: LeeLoo doesn't fit on small screens

---

content/ico/details.md
content/ico/tutorial.md
themes/fractalide/files/css/custom.css

Solution: make the sword resize with different screen sizes

Problem: sword ventures out into unrendered area

---

content/vision/partners.md
data/partners/nixcloud.nix

Solution: make a partners section

Problem: companies need distiguishing

---

content/ico/details.md

Solution: add video streaming for sports events and webcams

Problem: coin usage not explicit enough

---

content/ico/details.md

Solution: explicitly mention hard capped at ICO end
and add a few important features to the coin

Problem: total supply and currency features not clear

---

content/ico/details.md
themes/fractalide/files/js/ico.js

Solution: instead make it clear that every postponed means
the discount drops a bit. In other words, set ICO tranches = 365

Problem: ICO tranches are arbitrary
